#!/usr/bin/env bash

ANIME_REGEX="href=\"(.*html)\">(.*)</a>?.*title=\"(.*)\">"
INDEX=1
CHOICE=1
declare -a URL_ARR
function sscanf() 
{
  local str="$1"
  local format="$2"
  [[ "$str" =~ $format ]]
}

function release()
{
    OLD_IFS=$IFS
    IFS=$'\n'
    for x in $(curl -s http://www.yhdm.so/ | grep -Eo "a target=\"_blank\" href=\"/v/.*title=\".*\">")
    do
        sscanf $x $ANIME_REGEX
        echo $INDEX ${BASH_REMATCH[3]} " " ${BASH_REMATCH[2]}
        URL_ARR[INDEX]=${BASH_REMATCH[1]}
        let INDEX++
    done
    IFS=$OLD_IFS
}

#    CHOICE=$input
#    else
#        echo "emmm, $input not exist!"
#    fi

#mpv --fs $(curl -s http://www.yhdm.so/v/5341-1.html | grep -Eo "changeplay\(.*\\\$" | grep -Eo "http.*(?[A-Za-z0-9])")

release
echo "input index of the anime, Ctrl c to exit.."
read input
if [[ -v "URL_ARR[$input]" ]]; then
    echo "http://www.yhdm.so/${URL_ARR[$input]}"
    mpv --fs $(curl -s http://www.yhdm.so/${URL_ARR[$input]} | grep -Eo "changeplay\(.*\\\$" | grep -Eo "http.*(?[A-Za-z0-9])")
fi
